version = 5.8.0
archive_dir = /etc/letsencrypt/archive/torrift.com
cert = /etc/letsencrypt/live/torrift.com/cert.pem
privkey = /etc/letsencrypt/live/torrift.com/privkey.pem
chain = /etc/letsencrypt/live/torrift.com/chain.pem
fullchain = /etc/letsencrypt/live/torrift.com/fullchain.pem
[renewalparams]
account = cd1faa00fed340a66758245d97bdcefb
authenticator = dns-cloudflare
dns_cloudflare_propagation_seconds = 30
dns_cloudflare_credentials = /cloudflare.ini
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
