version: "3.8"
services: 
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports: 
      - "80:80/tcp"
      - "443:443/tcp"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
