services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    hostname: nginx
    dns: 
      - 192.168.1.21
    dns_search: 
      - tlnnegm.local
      - torrift.com
    extra_hosts:
      - "host.docker.internal:192.168.1.55"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./nginxdata:/etc/nginx:rw
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/www
    restart: unless-stopped
    networks:
      - vmnw

  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot_torrift
    volumes:
      - ./cloudflare.ini:/cloudflare.ini:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-lib:/var/lib/letsencrypt
    entrypoint: ["sleep", "inf"]
    restart: unless-stopped
    networks:
      - vmnw

networks:
  vmnw:
    external: true
    name: vm_nw
