events { }
http {
 	upstream scripts{
		server localhost:8080;
	}

	server  {
		listen 	80;
		server_name script.frpdock01t;
	
		location / {
		proxy_pass http://scripts;
		proxy_set_header Host $host;
		proxy_redirect off;
		}
	}
	upstream docker{
		server localhost:9000;
	}
	server  {
		listen 80;
		server_name docker.frpdock01t;
	
		location / {
		proxy_pass http://docker;
		proxy_set_header Host $host;
		proxy_redirect off;
		}
	}
}
	
