version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    hostname: nginx
    dns: 
      - 192.168.1.21
      - 192.168.1.22
    ports:
      - "80:80/tcp"
      - "442:442/tcp"
    volumes:
      - /mnt/data/Nginx_Server:/etc/nginx:ro
    restart: unless-stopped
    networks:
      - vmnw

networks:
  vmnw:
    external:
      name: vm_nw

